# Generated by Django 4.1.7 on 2023-11-01 16:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("clients", "0001_initial"),
        ("employees", "0003_subdepartment"),
        ("projects", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="subdepartment",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="employees.subdepartment",
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="client",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="clients.client",
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="status",
            field=models.CharField(
                choices=[
                    ("todo", "To Do"),
                    ("on_going", "On Going"),
                    ("on_hold", "On Hold"),
                    ("delayed", "On Going + Delay"),
                    ("client_delayed", "Delay by Client"),
                    ("in_review", "In Review"),
                    ("cancelled", "Cancelled"),
                    ("done", "Completed"),
                    ("delivered", "Delivered"),
                ],
                default="todo",
                max_length=255,
            ),
        ),
    ]
