# Generated by Django 4.1.7 on 2023-11-04 11:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("clients", "0002_alter_client_enquiry_alter_client_user"),
        ("employees", "0004_alter_department_department_lead_and_more"),
        ("projects", "0002_project_subdepartment_alter_project_client_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="project",
            name="client",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="clients.client",
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="department",
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="employees.department"),
        ),
        migrations.AlterField(
            model_name="project",
            name="referred_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="referred_by",
                to="employees.employee",
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="subdepartment",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="employees.subdepartment",
            ),
        ),
    ]
