# Generated by Django 4.1.7 on 2023-10-03 07:43

from decimal import Decimal

import django.db.models.deletion
import djmoney.models.fields
import versatileimagefield.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [migrations.swappable_dependency(settings.AUTH_USER_MODEL)]

    operations = [
        migrations.CreateModel(
            name="Department",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated", models.DateTimeField(auto_now=True)),
                (
                    "is_active",
                    models.BooleanField(
                        choices=[(True, "Yes"), (False, "No")],
                        default=True,
                        verbose_name="Mark as Active",
                    ),
                ),
                ("name", models.CharField(max_length=128)),
                ("description", models.TextField(blank=True, null=True)),
                (
                    "creator",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(app_label)s_%(class)s_creator",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={"ordering": ["-created"], "abstract": False},
        ),
        migrations.CreateModel(
            name="Designation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated", models.DateTimeField(auto_now=True)),
                (
                    "is_active",
                    models.BooleanField(
                        choices=[(True, "Yes"), (False, "No")],
                        default=True,
                        verbose_name="Mark as Active",
                    ),
                ),
                ("name", models.CharField(max_length=128)),
                ("description", models.TextField(blank=True, null=True)),
                (
                    "creator",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(app_label)s_%(class)s_creator",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={"ordering": ["-created"], "abstract": False},
        ),
        migrations.CreateModel(
            name="Grade",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated", models.DateTimeField(auto_now=True)),
                (
                    "is_active",
                    models.BooleanField(
                        choices=[(True, "Yes"), (False, "No")],
                        default=True,
                        verbose_name="Mark as Active",
                    ),
                ),
                ("name", models.CharField(max_length=128)),
                ("description", models.TextField(blank=True, null=True)),
                (
                    "creator",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(app_label)s_%(class)s_creator",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={"ordering": ["-created"], "abstract": False},
        ),
        migrations.CreateModel(
            name="Employee",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated", models.DateTimeField(auto_now=True)),
                (
                    "is_active",
                    models.BooleanField(
                        choices=[(True, "Yes"), (False, "No")],
                        default=True,
                        verbose_name="Mark as Active",
                    ),
                ),
                ("employee_id", models.CharField(max_length=128, unique=True)),
                ("first_name", models.CharField(max_length=300)),
                (
                    "middle_name",
                    models.CharField(blank=True, max_length=128, null=True),
                ),
                ("last_name", models.CharField(blank=True, max_length=128, null=True)),
                (
                    "gender",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("MALE", "Male"),
                            ("FEMALE", "Female"),
                            ("OTHER", "Other"),
                        ],
                        max_length=128,
                        null=True,
                    ),
                ),
                (
                    "marital_status",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("SINGLE", "Single"),
                            ("MARRIED", "Married"),
                            ("IN_A_RELATIONSHIP", "In a Relationship"),
                            ("DIVORCED", "Divorced"),
                            ("WIDOWED", "Widowed"),
                            ("OTHER", "Other"),
                        ],
                        max_length=128,
                        null=True,
                    ),
                ),
                (
                    "personal_email",
                    models.EmailField(blank=True, max_length=128, null=True),
                ),
                ("mobile", models.CharField(blank=True, max_length=128, null=True)),
                ("whatsapp", models.CharField(blank=True, max_length=128, null=True)),
                ("date_of_birth", models.DateField(blank=True, null=True)),
                ("religion", models.CharField(blank=True, max_length=128, null=True)),
                (
                    "photo",
                    versatileimagefield.fields.VersatileImageField(blank=True, null=True, upload_to="employees/photos/"),
                ),
                (
                    "ppoi",
                    versatileimagefield.fields.PPOIField(
                        default="0.5x0.5",
                        editable=False,
                        max_length=20,
                        verbose_name="Image PPOI",
                    ),
                ),
                (
                    "official_email",
                    models.EmailField(blank=True, max_length=128, null=True),
                ),
                (
                    "father_name",
                    models.CharField(blank=True, max_length=128, null=True),
                ),
                (
                    "father_mobile",
                    models.CharField(blank=True, max_length=128, null=True),
                ),
                (
                    "mother_name",
                    models.CharField(blank=True, max_length=128, null=True),
                ),
                (
                    "guardian_name",
                    models.CharField(blank=True, max_length=128, null=True),
                ),
                (
                    "guardian_mobile",
                    models.CharField(blank=True, max_length=128, null=True),
                ),
                (
                    "relationship_with_employee",
                    models.CharField(blank=True, max_length=128, null=True),
                ),
                ("date_of_joining", models.DateField(blank=True, null=True)),
                ("date_of_confirmation", models.DateField(blank=True, null=True)),
                (
                    "type_of_residence",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("SELF_OWNED", "Self Owned"),
                            ("FAMILY_OWNED", "Family Owned"),
                            ("SELF_RENTED", "Self Rented"),
                            ("FAMILY_RENTED", "Family Rented"),
                            ("COMPANY_RENTED", "Company Rented"),
                            ("COMPANY_OWNED", "Company Owned"),
                            ("SHARED", "Shared"),
                            ("OTHER", "Other"),
                        ],
                        max_length=128,
                        null=True,
                    ),
                ),
                (
                    "residence_name",
                    models.CharField(blank=True, max_length=128, null=True),
                ),
                ("residential_address", models.TextField(blank=True, null=True)),
                (
                    "residence_contact",
                    models.CharField(blank=True, max_length=128, null=True),
                ),
                (
                    "residential_postal_code",
                    models.CharField(blank=True, max_length=128, null=True),
                ),
                ("permanent_address", models.TextField(blank=True, null=True)),
                (
                    "permanent_postal_code",
                    models.CharField(blank=True, max_length=128, null=True),
                ),
                ("bank_name", models.CharField(blank=True, max_length=128, null=True)),
                (
                    "account_name",
                    models.CharField(blank=True, max_length=128, null=True),
                ),
                (
                    "account_number",
                    models.CharField(
                        blank=True,
                        max_length=128,
                        null=True,
                        verbose_name="Bank Account Number",
                    ),
                ),
                (
                    "ifsc_code",
                    models.CharField(
                        blank=True,
                        max_length=128,
                        null=True,
                        verbose_name="Bank IFSC Code",
                    ),
                ),
                (
                    "bank_branch",
                    models.CharField(blank=True, max_length=128, null=True),
                ),
                (
                    "pan_number",
                    models.CharField(
                        blank=True,
                        max_length=128,
                        null=True,
                        verbose_name="PAN Card Number",
                    ),
                ),
                (
                    "employment_type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("PERMANENT", "Permanent"),
                            ("PROBATION", "Probation"),
                            ("CONTRACT", "Contract"),
                            ("TEMPORARY", "Temporary"),
                        ],
                        max_length=128,
                        null=True,
                    ),
                ),
                (
                    "blood_group",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("a-positive", "A +Ve"),
                            ("b-positive", "B +Ve"),
                            ("ab-positive", "AB +Ve"),
                            ("o-positive", "O +Ve"),
                            ("a-negative", "A -Ve"),
                            ("b-negative", "B -Ve"),
                            ("ab-negative", "AB -Ve"),
                            ("o-negative", "O -Ve"),
                        ],
                        max_length=128,
                        null=True,
                    ),
                ),
                (
                    "basic_salary_currency",
                    djmoney.models.fields.CurrencyField(
                        choices=[("INR", "Indian Rupee"), ("USD", "US Dollar")],
                        default="INR",
                        editable=False,
                        max_length=3,
                    ),
                ),
                (
                    "basic_salary",
                    djmoney.models.fields.MoneyField(
                        decimal_places=2,
                        default=Decimal("0"),
                        default_currency="INR",
                        max_digits=14,
                    ),
                ),
                (
                    "hra_currency",
                    djmoney.models.fields.CurrencyField(
                        choices=[("INR", "Indian Rupee"), ("USD", "US Dollar")],
                        default="INR",
                        editable=False,
                        max_length=3,
                    ),
                ),
                (
                    "hra",
                    djmoney.models.fields.MoneyField(
                        decimal_places=2,
                        default=Decimal("0"),
                        default_currency="INR",
                        max_digits=14,
                    ),
                ),
                (
                    "other_allowance_currency",
                    djmoney.models.fields.CurrencyField(
                        choices=[("INR", "Indian Rupee"), ("USD", "US Dollar")],
                        default="INR",
                        editable=False,
                        max_length=3,
                    ),
                ),
                (
                    "other_allowance",
                    djmoney.models.fields.MoneyField(
                        decimal_places=2,
                        default=Decimal("0"),
                        default_currency="INR",
                        max_digits=14,
                    ),
                ),
                (
                    "transportation_allowance_currency",
                    djmoney.models.fields.CurrencyField(
                        choices=[("INR", "Indian Rupee"), ("USD", "US Dollar")],
                        default="INR",
                        editable=False,
                        max_length=3,
                    ),
                ),
                (
                    "transportation_allowance",
                    djmoney.models.fields.MoneyField(
                        decimal_places=2,
                        default=Decimal("0"),
                        default_currency="INR",
                        max_digits=14,
                    ),
                ),
                (
                    "creator",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(app_label)s_%(class)s_creator",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "department",
                    models.ForeignKey(
                        limit_choices_to={"is_active": True},
                        on_delete=django.db.models.deletion.PROTECT,
                        to="employees.department",
                    ),
                ),
                (
                    "designation",
                    models.ForeignKey(
                        limit_choices_to={"is_active": True},
                        on_delete=django.db.models.deletion.PROTECT,
                        to="employees.designation",
                    ),
                ),
                (
                    "grade",
                    models.ForeignKey(
                        limit_choices_to={"is_active": True},
                        on_delete=django.db.models.deletion.PROTECT,
                        to="employees.grade",
                    ),
                ),
                (
                    "hr_manager",
                    models.ForeignKey(
                        blank=True,
                        limit_choices_to={"is_active": True},
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="employee_hr_manager",
                        to="employees.employee",
                        verbose_name="HR",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        limit_choices_to={"is_active": True},
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="employee",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={"ordering": ["-created"], "abstract": False},
        ),
        migrations.AddField(
            model_name="department",
            name="department_lead",
            field=models.ForeignKey(
                blank=True,
                limit_choices_to={"is_active": True},
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="department_lead",
                to="employees.employee",
            ),
        ),
        migrations.CreateModel(
            name="Point",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated", models.DateTimeField(auto_now=True)),
                (
                    "is_active",
                    models.BooleanField(
                        choices=[(True, "Yes"), (False, "No")],
                        default=True,
                        verbose_name="Mark as Active",
                    ),
                ),
                (
                    "points",
                    models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True),
                ),
                ("reason", models.CharField(blank=True, max_length=128, null=True)),
                (
                    "year",
                    models.IntegerField(
                        choices=[
                            (1950, 1950),
                            (1951, 1951),
                            (1952, 1952),
                            (1953, 1953),
                            (1954, 1954),
                            (1955, 1955),
                            (1956, 1956),
                            (1957, 1957),
                            (1958, 1958),
                            (1959, 1959),
                            (1960, 1960),
                            (1961, 1961),
                            (1962, 1962),
                            (1963, 1963),
                            (1964, 1964),
                            (1965, 1965),
                            (1966, 1966),
                            (1967, 1967),
                            (1968, 1968),
                            (1969, 1969),
                            (1970, 1970),
                            (1971, 1971),
                            (1972, 1972),
                            (1973, 1973),
                            (1974, 1974),
                            (1975, 1975),
                            (1976, 1976),
                            (1977, 1977),
                            (1978, 1978),
                            (1979, 1979),
                            (1980, 1980),
                            (1981, 1981),
                            (1982, 1982),
                            (1983, 1983),
                            (1984, 1984),
                            (1985, 1985),
                            (1986, 1986),
                            (1987, 1987),
                            (1988, 1988),
                            (1989, 1989),
                            (1990, 1990),
                            (1991, 1991),
                            (1992, 1992),
                            (1993, 1993),
                            (1994, 1994),
                            (1995, 1995),
                            (1996, 1996),
                            (1997, 1997),
                            (1998, 1998),
                            (1999, 1999),
                            (2000, 2000),
                            (2001, 2001),
                            (2002, 2002),
                            (2003, 2003),
                            (2004, 2004),
                            (2005, 2005),
                            (2006, 2006),
                            (2007, 2007),
                            (2008, 2008),
                            (2009, 2009),
                            (2010, 2010),
                            (2011, 2011),
                            (2012, 2012),
                            (2013, 2013),
                            (2014, 2014),
                            (2015, 2015),
                            (2016, 2016),
                            (2017, 2017),
                            (2018, 2018),
                            (2019, 2019),
                            (2020, 2020),
                            (2021, 2021),
                            (2022, 2022),
                            (2023, 2023),
                            (2024, 2024),
                        ],
                        default=2023,
                    ),
                ),
                (
                    "month",
                    models.CharField(
                        choices=[
                            ("1", "January"),
                            ("2", "February"),
                            ("3", "March"),
                            ("4", "April"),
                            ("5", "May"),
                            ("6", "June"),
                            ("7", "July"),
                            ("8", "August"),
                            ("9", "September"),
                            ("10", "October"),
                            ("11", "November"),
                            ("12", "December"),
                        ],
                        default=10,
                        max_length=128,
                    ),
                ),
                (
                    "creator",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(app_label)s_%(class)s_creator",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "employee",
                    models.ForeignKey(
                        limit_choices_to={"is_active": True},
                        on_delete=django.db.models.deletion.PROTECT,
                        to="employees.employee",
                    ),
                ),
            ],
            options={
                "verbose_name": "Point",
                "verbose_name_plural": "Points",
                "unique_together": {("employee", "year", "month")},
            },
        ),
    ]
