# Generated by Django 4.1.7 on 2023-10-31 07:59

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [("employees", "0001_initial")]

    operations = [
        migrations.RemoveField(model_name="employee", name="hr_manager"),
        migrations.DeleteModel(name="Point"),
    ]
