# Generated by Django 4.1.7 on 2023-11-04 11:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("employees", "0004_alter_department_department_lead_and_more"),
        ("marketing", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="enquiry",
            name="department",
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="employees.department"),
        ),
        migrations.AlterField(
            model_name="enquiryfollowup",
            name="enquiry",
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="marketing.enquiry"),
        ),
    ]
