# Generated by Django 4.1.7 on 2023-11-04 11:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("projects", "0003_alter_project_client_alter_project_department_and_more"),
        ("employees", "0004_alter_department_department_lead_and_more"),
        ("tasks", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="task",
            name="assigned_to",
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="employees.employee"),
        ),
        migrations.AlterField(
            model_name="task",
            name="project",
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="projects.project"),
        ),
    ]
