# Generated by Django 4.2 on 2025-11-21 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_alter_task_assigned_to_alter_task_project'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='start_from',
            field=models.DateTimeField(),
        ),
    ]
