# Generated by Django 4.2 on 2025-11-21 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_alter_task_start_from'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='end_before',
            field=models.DateTimeField(),
        ),
    ]
