# Generated by Django 4.2 on 2025-11-21 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0005_task_attachment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('todo', 'To Do'), ('on_going', 'On Going'), ('delayed', 'On Going + Delay'), ('on_hold', 'On Hold'), ('rework', 'Rework'), ('cancelled', 'Cancelled'), ('in_review', 'In Review'), ('done', 'Done')], default='todo', max_length=255),
        ),
    ]
